### ISSUE TITLE
Do getAllDocuments and/or deleteDocument throw exceptions when they fail?

### ISSUE THREAD

**Issue by TDuffinNTU** [GregoryConrad/mimir#216]
This isn't mentioned in the documents, but it might be good to know so I can make sure to handle exceptions before they come up randomly :)

**Comment by GregoryConrad** [comment]
All async methods exposed in the API are fallible (although it is unlikely they ever will, unless it’s something like you need to specify a valid primary key).

I’ll leave this open until I can add a blurb to the documentation about it later 👌
