### ISSUE TITLE
Adding this package increases the size of the Android app by 160.5 MB

### ISSUE THREAD

**Issue by siddharthadevops** [GregoryConrad/mimir#225]
Is this behavior normal?

**Comment by GregoryConrad** [comment]
Yup, unfortunately there’s not much I can do about it until the “Native Assets” feature is released in Dart 

I played around with some size optimizations before and unfortunately they didn’t help all that much.

Is 160 MB the added size of the bundle, or the added size on device?

**Comment by siddharthadevops** [comment]
In the bundle, on device ~70MB

**Comment by GregoryConrad** [comment]
That sounds about right. I'll keep this open until I can add a blurb to docs that app sizes may be increased substantially until native assets come around
