### ISSUE TITLE
Problem with project building

### ISSUE THREAD

**Issue by AndriyChaban** [GregoryConrad/mimir#316]
I cannot build a cloned project in order to generate embedded libraries. On Windows and Linux I get the same error:
error: failed to run custom build command for embedded_milli v0.0.0 (/home/kali/Desktop/mimir/mimir/packages/mimir/native)

Caused by:
process didn't exit successfully: /home/kali/Desktop/mimir/mimir/target/release/build/embedded_milli-19194df039e45a31/build-script-build (exit status: 101)
--- stdout
cargo:rerun-if-changed=src/api.rs

--- stderr
thread 'main' panicked at packages/mimir/native/build.rs:32:43:
called Result::unwrap() on an Err value: External command failure.
missing pubspec.lock in /home/kali/Desktop/mimir/mimir/packages/mimir/native/..

Caused by:
missing pubspec.lock in /home/kali/Desktop/mimir/mimir/packages/mimir/native/..
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by AndriyChaban** [comment]
I cannot build a cloned project in order to generate embedded libraries. On Windows and Linux I get the same error: 
error: failed to run custom build command for `embedded_milli v0.0.0 (/home/kali/Desktop/mimir/mimir/packages/mimir/native)`

Caused by:
  process didn't exit successfully: `/home/kali/Desktop/mimir/mimir/target/release/build/embedded_milli-19194df039e45a31/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=src/api.rs

  --- stderr
  thread 'main' panicked at packages/mimir/native/build.rs:32:43:
  called `Result::unwrap()` on an `Err` value: External command failure.
  missing pubspec.lock in /home/kali/Desktop/mimir/mimir/packages/mimir/native/..

  Caused by:
      missing pubspec.lock in /home/kali/Desktop/mimir/mimir/packages/mimir/native/..
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by GregoryConrad** [comment]
Hi 👋

You're probably just missing a step or two of the setup instructions, see https://github.com/GregoryConrad/mimir/blob/main/CONTRIBUTING.md

My guess is you didn't do a `melos bs`

**Comment by AndriyChaban** [comment]
Hi!
Tried to follow the steps (didn't see them before). On Linux it compiled successfully. But Windows gives me the following error:
```
failed to run custom build command for `embedded_milli v0.0.0 (C:\Users\chaba\StudioProjects\mimir\packages\mimir\native)`

Caused by:
  process didn't exit successfully: `C:\...\mimir\target\release\build\embedded_milli-42c57bc2c2eb55e4\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=src/api.rs

  --- stderr
  thread 'main' panicked at packages\mimir\native\build.rs:32:43:
  called `Result::unwrap()` on an `Err` value: External command failure.
  ffigen could not find LLVM. Please supply --llvm-path to flutter_rust_bridge_codegen, e.g.:

      flutter_rust_bridge_codegen .. --llvm-path <path_to_llvm>

  Caused by:
      ffigen could not find LLVM. Please supply --llvm-path to flutter_rust_bridge_codegen, e.g.:

          flutter_rust_bridge_codegen .. --llvm-path <path_to_llvm>
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by GregoryConrad** [comment]
Have you installed LLVM and is it available on your PATH? I checked the windows CI and it looks like if you install LLVM v15 you should be all set.

**Comment by AndriyChaban** [comment]
Thank you very much! It helped!
