### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by siddharthadevops** [GregoryConrad/mimir#351]
Hi,
It would be possible to update the dependencies of this package. I need to update firebase auth to solve a link problem but I can't because there seems to be a conflict with the web version.

Because no versions of flutter_mimir match >0.1.0 <0.2.0 and flutter_mimir 0.1.0 depends on mimir ^0.1.0, flutter_mimir ^0.1.0 requires mimir ^0.1.0.
And because no versions of mimir match >0.1.0 <0.2.0, flutter_mimir ^0.1.0 requires mimir 0.1.0.
And because mimir 0.1.0 depends on flutter_rust_bridge 2.1.0 which depends on web ^0.5.0, flutter_mimir ^0.1.0 requires web ^0.5.0.
And because firebase_auth >=5.3.1 depends on firebase_auth_web ^5.13.2 which depends on web ^1.0.0, flutter_mimir ^0.1.0 is incompatible with firebase_auth >=5.3.1.
So, because weebu depends on both firebase_auth 5.3.1 and flutter_mimir ^0.1.0, version solving failed.

Many Thanks!

**Comment by GregoryConrad** [comment]
I'll try to upgrade to `flutter_rust_bridge` 2.5 soon, which seems to make the `web` constraint looser (`< 2.0`). Not sure why dependabot didn't open up PRs for any of the recent versions.

Might take me a second to get around to this manually. Really busy past few weeks

**Comment by GregoryConrad** [comment]
Oh wow, I'm just an idiot, Mimir already has FRB 2.4 (from dependabot), which has the looser `web` requirement, and I just didn't release a new version. I'll release a new version now (give it a few hours to go thru CI and be available).

**Comment by GregoryConrad** [comment]
@siddharthadevops should be fixed in `0.1.1`

**Comment by siddharthadevops** [comment]
@GregoryConrad problem solved.
 Many Thanks!!!!!!
